version: "3.7"

services:

  bot:
    container_name: "${BOT_NAME}-bot"
    build:
      context: .
    stop_signal: SIGINT
    volumes:
      - ./app:/src/app
    command: >
      sh -c "
        #python ./app/website/manage.py migrate --fake-initial &&
        #python ./app/website/manage.py makemigrations whatisthere &&
        python ./app/website/manage.py createsuperuser --noinput &&
        python ./app/website/manage.py runserver 0.0.0.0:8000&
        python -O bot.py"
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    environment:
      DB_HOST: database
      REDIS_HOST: redis
    depends_on:
      - redis
    networks:
      - botnet

  redis:
    container_name: "${BOT_NAME}-redis"
    image: redis:7-alpine
    env_file:
      - ".env"
    ports:
      - "6377:6379"
    volumes:
      - ./redisdata:/var/lib/redis
    restart: unless-stopped
    networks:
      - botnet



networks:
  botnet:
    name: botnet
    driver: bridge
