# Generated by Django 4.2.1 on 2023-06-11 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('pack_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID Пакету')),
                ('commission', models.IntegerField(verbose_name='Комісія у відсотках')),
                ('trigger', models.IntegerField(verbose_name='Тригерна ціна, грн')),
                ('under', models.IntegerField(verbose_name='Фікована комісія, грн')),
                ('minimal', models.IntegerField(verbose_name='Мінімальна ціна угоди, грн')),
                ('maximal', models.IntegerField(verbose_name='Максимальна ціна угоди, грн')),
                ('name', models.CharField(max_length=255, verbose_name='Назва пакунку')),
                ('description', models.CharField(max_length=500, verbose_name='Інформація для амдіна')),
            ],
            options={
                'verbose_name': 'комісійний пакет',
                'verbose_name_plural': 'комісійні пакети',
                'db_table': 'commissions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Телеграм ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('status', models.CharField(choices=[('ACTIVE', 'Активний'), ('BANNED', 'Забанений')], default='UNAUTHORIZED', verbose_name='Статус')),
                ('type', models.CharField(choices=[('ADMIN', 'Адмін'), ('USER', 'Клієнт'), ('MODERATOR', 'Модератор')], default='USER', verbose_name='Права')),
                ('balance', models.BigIntegerField(default=0, verbose_name='Баланс')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Про себе')),
                ('ban_comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Причина бану')),
                ('time', models.CharField(default='*', max_length=10, verbose_name='Дозволені години')),
                ('info', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Коментар для адміністраторів')),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatistherebot.commission', verbose_name='Комісійний пакунок')),
            ],
            options={
                'verbose_name': 'юзер',
                'verbose_name_plural': 'юзери',
                'db_table': 'users',
            },
        ),
    ]
