# Generated by Django 4.2.1 on 2023-11-04 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatistherebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'користувач', 'verbose_name_plural': 'користувачі'},
        ),
        migrations.AlterField(
            model_name='user',
            name='commission',
            field=models.ForeignKey(blank=True, db_column='commission_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatistherebot.commission', verbose_name='Комісійний пакунок'),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='commission',
            new_name='commission_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='info',
        ),
        migrations.AddField(
            model_name='user',
            name='bankcard',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Банківська карта'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Інформація для амдіна'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.CharField(default='*', max_length=10, verbose_name='Години сповіщень'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Адмін'), ('USER', 'Користувач'), ('MODERATOR', 'Модератор')], default='USER', verbose_name='Права'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення')),
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('invite_link', models.CharField(max_length=150, unique=True, verbose_name='Запрошувальне посилання')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Вільний'), ('BUSY', 'Зайнятий')], default='AVAILABLE', verbose_name='Статус чату')),
                ('admin_required', models.BooleanField(choices=[(True, 'Потрібна'), (False, 'Не потрібна')], default=False, verbose_name='Допомога в чаті')),
                ('reason', models.CharField(blank=True, max_length=150, null=True, verbose_name='Причина')),
                ('admin_id', models.ForeignKey(blank=True, db_column='admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatistherebot.user', verbose_name='Адмін чату')),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чати',
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення')),
                ('post_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Пост Id')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('about', models.CharField(max_length=800, verbose_name='Опис')),
                ('price', models.IntegerField(default=0, verbose_name='Ціна поста, грн')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активний'), ('BUSY', 'Зайнятий в угоді'), ('DONE', 'Завершений'), ('DISABLED', 'Відхилений адміністратором'), ('MODERATE', 'Очікує схвалення адміністратором'), ('WAIT', 'Очікує публікації в черзі')], default='MODERATE', verbose_name='Статус')),
                ('message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Повідомлення в основному каналі')),
                ('admin_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Повідомлення в адмін каналі')),
                ('reserv_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Повідомлення в резервному каналі')),
                ('post_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='Посилання на пост')),
                ('media_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='Посилання на медіа')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='whatistherebot.user', verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'пости',
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення')),
                ('deal_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id угоди')),
                ('price', models.IntegerField(default=0, verbose_name='Ціна угоди, грн')),
                ('commission', models.IntegerField(editable=False, verbose_name='Комісія сервісу, грн')),
                ('payed', models.IntegerField(default=0, verbose_name='Оплачено, грн')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('BUSY', 'Виконується в чаті'), ('DONE', 'Завершена'), ('DISABLED', 'Відхилена адміністратором'), ('MODERATE', 'Очікує схвалення поста'), ('WAIT', 'Очікує публікації поста')], default='MODERATE', verbose_name='Статус')),
                ('rating', models.IntegerField(blank=True, choices=[(None, 'Немає'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Рейтингова оцінка')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Відгук')),
                ('next_activity_date', models.DateTimeField(blank=True, help_text='*Визначається автоматично', null=True, verbose_name='Дата перевірки активності')),
                ('activity_confirm', models.BooleanField(choices=[(True, 'Підтверджена'), (False, 'Не підтверджена')], default=True, verbose_name='Підтвердження активності')),
                ('log', models.CharField(editable=False, null=True, verbose_name='Історія угоди')),
                ('chat_id', models.ForeignKey(blank=True, db_column='chat_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatistherebot.room', verbose_name='Чат угоди')),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='whatistherebot.user', verbose_name='Замовник')),
                ('executor_id', models.ForeignKey(blank=True, db_column='executor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor_id', to='whatistherebot.user', verbose_name='Виконавець')),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='whatistherebot.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'угода',
                'verbose_name_plural': 'угоди',
                'db_table': 'deals',
            },
        ),
    ]
